JWMaps/Models/TerritoryMap.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace JWMaps.Models
{
    public class TerritoryMap
    {
        public int Id { get; set; }

        public DateTime CreationDate { get; set; }

        public List<Householder> Householders { get; set; }

        [Required]
        public int CongregationId { get; set; }

        [Required]
        public string UserId { get; set; }

        public string Neighbourhood { get; set; }

        public TerritoryMap()
        {
            this.CreationDate = DateTime.Now;
        }
    }
}

JWMaps/Controllers/TerritoryMapsController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using JWMaps.Models;
using JWMaps.ViewModel;
using System;
using GoogleMaps.LocationServices;
using System.Net.Http;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System.Configuration;
using BogdanM.LocationServices.GoogleMaps;
using BogdanM.LocationServices.Core;
using System.Data.SqlClient;

namespace JWMaps.Controllers
{
    public class TerritoryMapsController : Controller
    {
        private ApplicationDbContext _context;

        public TerritoryMapsController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: TerritoryMaps
        public ActionResult Index()
        {
            if (User.IsInRole(RoleName.CanAdministrate))
            {
                List<ListAllTerritoryMapsViewModel> usersMaps = new List<ListAllTerritoryMapsViewModel>();

                foreach (var user in _context.Users.ToList())
                {
                    var maps = _context.TerritoryMaps.Where(t => t.UserId == user.Id).ToList();

                    if (maps.Count > 0)
                    {
                        ListAllTerritoryMapsViewModel viewModel = new ListAllTerritoryMapsViewModel
                        {
                            TerritoryMaps = maps,
                            User = user
                        };

                        usersMaps.Add(viewModel);
                    }
                }


                return View("ListAllTerritoryMaps", usersMaps);
            }

            ApplicationUser myUser = GetUser();

            var territoryMaps = _context.TerritoryMaps.Where(t => t.UserId.Equals(myUser.Id));

            return View(territoryMaps.ToList());
        }

        private ApplicationUser GetUser()
        {
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindByNameAsync(User.Identity.Name).Result;

            return user;
        }

        // GET: TerritoryMaps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            TerritoryMap territoryMap = _context.TerritoryMaps.Find(id);
            if (territoryMap == null)
                return HttpNotFound();

            return View(territoryMap);
        }

        // GET: TerritoryMaps/Create
        public ActionResult Create()
        {
            return View(new TerritoryMapViewModel { Neighbourhoods = new List<string>() });
        }

        [HttpPost]
        public ActionResult GetNeighbourhoodByMapType(string mapType)
        {
            string categoryName = GetCategoryName(mapType);
            Category category = (Category)System.Enum.Parse(typeof(Category), categoryName);

            if (String.IsNullOrEmpty(categoryName))
                return Json(new { succes = false, JsonRequestBehavior.AllowGet });

            ApplicationUser user = GetUser();

            var categoryParam = new SqlParameter("@category", (int)category);
            var congregationIdParam = new SqlParameter("@congregationId",user.CongregationId);
            var neighbourhoods = _context.Database.SqlQuery<NeighbourhoodsVisits>("GetNeighbourhoodsByLastVisited @category, @congregationId", categoryParam, congregationIdParam).ToList();

            var max = (neighbourhoods.ToList().Count < 3) ? neighbourhoods.ToList().Count : 3;

            var territoryMapViewModel = new TerritoryMapViewModel
            {
                Neighbourhoods = neighbourhoods.Select(n => n.Neighbourhood),
                NeighbourhoodsSuggestion = neighbourhoods.Select(n => n.Neighbourhood).Take(max),
            };

            return Json(new { success = true, territoryMapViewModel, JsonRequestBehavior.AllowGet });
        }

        class NeighbourhoodsVisits
        {
            public DateTime? LastVisit { get; set; }

            public string Neighbourhood { get; set; }
        }

        private string GetCategoryName(string mapType)
        {
            if (mapType.Equals("Comercial"))
                return "Business";
            else if ((mapType.Equals("Residência")))
                return "House";
            else
                return null;
        }

        // POST: TerritoryMaps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] TerritoryMap territoryMap)
        {
            if (ModelState.IsValid)
            {
                _context.TerritoryMaps.Add(territoryMap);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(territoryMap);
        }

        public ActionResult Show(int id)
        {
            var householders = _context.TerritoryMaps.Include(t => t.Householders.Select(h => h.Visits))
                                                     .SingleOrDefault(t => t.Id == id).Householders.ToList();

            return View(householders);
        }

        public ActionResult SelectTerritoryType(int id)
        {
            var territoryTypeViewModel = new TerritoryTypeViewModel();
            return PartialView("_TerritoryTypeChoice", territoryTypeViewModel);
        }

        public ActionResult New(TerritoryMapViewModel territoryMapViewModel)
        {
            try
            {
                var locationService = new GoogleLocationService(ConfigurationManager.AppSettings["GooglePlaceAPIKey"]);
                var googleMapsService = new GoogleMapsService(ConfigurationManager.AppSettings["GooglePlaceAPIKey"]);

                ApplicationUser user = GetUser();
                var householdersToVisit = GetHouseholdersToVisit(territoryMapViewModel, user);

                //Vou mudar isso para refletir as mudanças no algoritmo de montagem dos mapas
                territoryMapViewModel.MaxNumberOfHouseholders = 5;
                territoryMapViewModel.MaxDistanceAmongHouseholders = 5000;


                if (householdersToVisit == null)
                    return View("NotAvailableHouseholders");

                var newTerritoryMap = new TerritoryMap()
                {
                    CongregationId = user.CongregationId,
                    Neighbourhood = territoryMapViewModel.selectedNeighbourhood,
                    Householders = new List<Householder>(),
                    UserId = user.Id
                };

                if (householdersToVisit.Count > 0)
                {
                    var firstHouseholderToVisit = householdersToVisit.First();
                    newTerritoryMap.Householders.Add(firstHouseholderToVisit);
                    householdersToVisit.Remove(firstHouseholderToVisit);

                    for (int i = 0; newTerritoryMap.Householders.Count() < territoryMapViewModel.MaxNumberOfHouseholders && i < householdersToVisit.Count(); i++)
                    {
                        var distance = googleMapsService.GetDistance(new LatLng((decimal)firstHouseholderToVisit.Latitude, (decimal)firstHouseholderToVisit.Longitude),
                                                                      new LatLng((decimal)householdersToVisit[i].Latitude, (decimal)householdersToVisit[i].Longitude));

                        if (distance <= territoryMapViewModel.MaxDistanceAmongHouseholders)
                        {
                            newTerritoryMap.Householders.Add(householdersToVisit[i]);
                        }
                    }

                    _context.TerritoryMaps.Add(newTerritoryMap);
                    _context.SaveChanges();
                }
                else
                {
                    return View("NoMap");
                }

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                System.Threading.Thread.Sleep(1000);
                return New(territoryMapViewModel);
            }
        }

        private List<Householder> GetHouseholdersToVisit(TerritoryMapViewModel territory, ApplicationUser user)
        {
            var myCongregationTerritoriesMap = _context.TerritoryMaps.Include(t => t.Householders).Where(t => t.CongregationId == user.CongregationId);
            List<Householder> houseHoldersInMap = new List<Householder>();

            foreach (var terrytoryMap in myCongregationTerritoriesMap)
                houseHoldersInMap.AddRange(terrytoryMap.Householders);

            var categoryParam = new SqlParameter("@category", (int) territory.Category);
            var congregationIdParam = new SqlParameter("@congregationId", user.CongregationId);
            var neighbourhoodParam = new SqlParameter("@neighbourhood", territory.selectedNeighbourhood);
            var householdersToVisitIds = _context.Database.SqlQuery<int>("GetLastVisitedPeople @category, @congregationId, @neighbourhood", categoryParam, congregationIdParam, neighbourhoodParam).ToList();

            var householdersToVisit = _context.Householders.Include(h => h.Visits).Where(h => householdersToVisitIds.Any(p => p == h.Id)).ToList();
            householdersToVisit = householdersToVisit.OrderBy(h => householdersToVisitIds.IndexOf(h.Id)).ToList();

            return householdersToVisit;
        }

        public ActionResult List()
        {
            var store = new UserStore<ApplicationUser>(new ApplicationDbContext());
            var userManager = new UserManager<ApplicationUser>(store);
            ApplicationUser user = userManager.FindByNameAsync(User.Identity.Name).Result;

JWMaps/Views/TerritoryMaps/Create.cshtml
@model JWMaps.ViewModel.TerritoryMapViewModel

@{
    ViewBag.Title = "Criando o mapa";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Como será o mapa?</h2>

<div>
    <div class="form-group">
        <label>Tipo de endereço</label>
        @Html.EnumDropDownListFor(m => m.Category, "-- Selecione um tipo de endereço --", new { @class = "form-control", @selected="selected" })
        @Html.ValidationMessageFor(m => m.Category)
    </div>
    <div id="suggestion"></div>
    <div class="form-group" id="neighbourhood-div">
        <label>Bairro</label>
        <select class="form-control" id="TerritoryMap_Neighbourhood" name="TerritoryMap.Neighbourhood"></select>
    </div>

    <div id="divLoading">
    </div>

    <button id="create-map-btn" type="submit" class="btn btn-primary" @*onclick='showLoading(); newMap();'*@>Criar!</button>
</div>
<br />
<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section scripts
{
    <script type="text/javascript" language="javascript">
        $(document).ready(function () {            
            main();
        });

        function main() {
            $("#neighbourhood-div").hide();
            $("#create-map-btn").hide();
            setDefaultSelectedCategory();
            $("#create-map-btn").on("click", function () {
                showLoading();
                newMap();
            });

            $("#Category").change(function () {
                var mapType = $("#Category").find(":selected").text();
                $("#TerritoryMap_Neighbourhood").empty();

                onMapCategoryOptionSelected(mapType);
            })
        }

        function setDefaultSelectedCategory() {
            //$("#Category selectz").sele
        }

        function onMapCategoryOptionSelected(mapType) {
            $.ajax({
                    url: "@Url.Action("GetNeighbourhoodByMapType", "TerritoryMaps")",
                    type: "POST",
                    data: { 'maptype': mapType },
                    dataType: "json",
                    success: function (response) {
                        console.log(response);
                        if (response.success) {
                            showSelect(response.territoryMapViewModel.Neighbourhoods);
                            showSuggestedNeighbourhoods(response.territoryMapViewModel.NeighbourhoodsSuggestion);
                        }
                        else {
                            hideSelect();
                        }
                    },
                    error: function (xhr, status, exception) {
                        console.log("Error: " + exception + ", Status: " + status);
                    }
            });
        }

        function showSelect(neighbourhoods) {
            $("#neighbourhood-div").fadeIn();
            setTimeout(function () { $("#create-map-btn").fadeIn() }, 500);

            $.each(neighbourhoods, function (index, neighbourhood) {
                $("#TerritoryMap_Neighbourhood").append($('<option>', { value: index, text: neighbourhood}))
            })
        }

        function hideSelect() {
            $("#neighbourhood-div").fadeOut();
            setTimeout(function () { $("#create-map-btn").fadeOut() }, 500);
        }

        function showLoading() {
            $("div#divLoading").addClass('show');
        }

        function showSuggestedNeighbourhoods(suggestedNeighbourhoods) {
            $("#suggestion").empty();
            var $label = $("<label>").text("Bairros sugeridos");
            var $ul = $("<ul>");
            
            $("#suggestion").append($label);
            $("#suggestion label").after($ul);

            suggestedNeighbourhoods.forEach(function (suggestion) {
                $ul.append($("<li>" + suggestion + "</li>"))
            });
        }

        function newMap() {
            $.ajax({
                url: "@Url.Action("New", "TerritoryMaps")",
                type: "POST",
                data: {
                    "TerritoryMapViewModel": {
                        "selectedNeighbourhood": $("#TerritoryMap_Neighbourhood option:selected").text(),
                        "Category" : getCategory($("#Category option:selected").text())
                    }
                },
                async: false,
                dataType: "json",
                succes: window.location.replace("../territoryMaps")
            });
        }

        function getCategory(text) {
            if (text == "Comercial") {
                return "Business";
            }
            else if (text == "Residência") {
                return "House";
            }
        }
    </script>
}

JWMaps/Views/TerritoryMaps/Delete.cshtml
@model JWMaps.Models.TerritoryMap

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TerritoryMap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JWMaps/Views/TerritoryMaps/Details.cshtml
@model JWMaps.Models.TerritoryMap

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TerritoryMap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

JWMaps/Views/TerritoryMaps/Edit.cshtml
@model JWMaps.Models.TerritoryMap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TerritoryMap</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

JWMaps/Views/TerritoryMaps/Index.cshtml
@model List<JWMaps.Models.TerritoryMap>

@{
    ViewBag.Title = "Meus territórios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Minha lista de territórios</h2>

<p>@Html.ActionLink("Novo território", "Create", "TerritoryMaps", null, new { @class = "btn btn-primary new-territory" })</p>
@*<button id="new-territory" class="btn btn-primary">Novo território</button>*@

<br />

<table id="territoryMaps" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Mapa</th>
            <th>Bairro</th>
            <th>Apagar</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@Html.ActionLink("Mapa " + (i+1) , "Show", "TerritoryMaps", new { id = Model[i].Id }, null)</td>
                <td>@Model[i].Neighbourhood</td>                
                <td><button class="btn-link js-delete" data-id=@Model[i].Id>deletar</button></td>
            </tr>
        }
    </tbody>
</table>

@*<div class="modal" id="modal"></div>*@

@section scripts
{
<script>
        $(document).ready(function () {
            $("#territoryMaps").DataTable();

            $(".js-delete").on("click", function () {
                var tr = $(this).closest('tr');
                var button = $(this);

                bootbox.confirm("Você tem certeza que deseja devolver esse mapa?", function (result) {
                    if (result) {
                        $.ajax({
                            type: "POST",
                            url: "@Url.Action("Delete","TerritoryMaps")",
                            ajaxasync: true,
                            data: { id: button.attr("data-id") },
                            success: tr.remove()
                        });
                    }
                });
            });

            //$(function () {
            //    $("#new-territory").click(function () {
            //        $("#modal").load("SelectTerritoryType?id=" + 1, function () {
            //            $("#modal").modal();
            //        });
            //     });
            //});
        });
</script>
}

JWMaps/Views/TerritoryMaps/ListAllTerritoryMaps.cshtml
@model List<JWMaps.ViewModel.ListAllTerritoryMapsViewModel>

@{
    ViewBag.Title = "Meus territórios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Minha lista de territórios</h2>

<p>@Html.ActionLink("Novo território", "Create", "TerritoryMaps", null, new { @class = "btn btn-primary" })</p>

<br />

<table id="territoryMaps" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>nth</th>            
            <th>Dono</th>
            <th>Bairro</th>
            <th>Data de criação</th>
            <th>Apagar</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            for (int i = 0; i < item.TerritoryMaps.Count; i++)
            {
                <tr>
                    <td>@Html.ActionLink("Mapa " + (i + 1), "Show", "TerritoryMaps", new { id = item.TerritoryMaps[i].Id }, null)</td>
                    <td>@item.User.UserName</td>
                    <td>@item.TerritoryMaps[i].Neighbourhood</td>
                    <td>@item.TerritoryMaps[i].CreationDate</td>
                    <td><button class="btn btn-link js-delete" data-id=@item.TerritoryMaps[i].Id>deletar</button></td>
                </tr>
            }
        }
    </tbody>
</table>

@section scripts
{
    <script>
        $(document).ready(function () {
            $("#territoryMaps").DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
                }
            });

            $(".js-delete").on("click", function () {
                var tr = $(this).closest('tr');
                var button = $(this);

                bootbox.confirm("Você tem certeza que deseja devolver esse mapa?", function (result) {
                    if (result) {
                        $.ajax({
                            type: "POST",
                            url: "@Url.Action("Delete","TerritoryMaps")",
                            ajaxasync: true,
                            data: { id: button.attr("data-id") },
                            success: tr.remove()
                        });
                    }
                });
            });
        });
    </script>
}

JWMaps/Views/TerritoryMaps/NoMap.cshtml
@{
    ViewBag.Title = "Nenhum mapa atende a esses parâmetros";
}

<div class="jumbotron">
    <h1>Ops...</h1>
    <p>Não foi possível formar nenhum mapa com os parâmetros fornecidos. Tente mudar o bairro ou o tipo  de mapa (comercial ou residencial).</p>
</div>
<div>
    @Html.ActionLink("Voltar", "Index")
</div>

JWMaps/Views/TerritoryMaps/NotAvailableHouseholders.cshtml
@{
    ViewBag.Title = "Ops...";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Não há endereços disponíveis com essas configurações.</h2>

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

JWMaps/Views/TerritoryMaps/SetVisit.cshtml
@model JWMaps.ViewModel.VisitViewModel
@{
    ViewBag.Title = "SetVisit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Como foi a visita?</h2>

@using (Html.BeginForm("SaveVisit", "TerritoryMaps", FormMethod.Post))
{    
    <div class="form-group">
        <label>Quem visitou?</label>
        @Html.ValidationMessageFor(t => t.PublisherName)
        @Html.DropDownListFor(t => t.PublisherName, new SelectList(Model.Publishers, "Name", "Name"), new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Como foi a visita?</label>
        @Html.TextAreaFor(t => t.VisitDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(t => t.VisitDescription)
    </div>
    @Html.HiddenFor(t => t.VisitedHouseHolder.Id)
    <button type="submit" class="btn btn-primary">Salvar</button>
}
<br />

JWMaps/Views/TerritoryMaps/Show.cshtml
@model List<JWMaps.Models.Householder>

@{
    ViewBag.Title = "Mapa de território";
}

<h2>Mapa de território</h2>

<table id="householders" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Número do mapa</th>
            <th>Nome</th>
            <th>Endereço</th>
            <th>Data da última visita</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.Count; i++)
        {
            <tr>
                <td>@(i + 1)</td>
                @if (Model[i].Name != null)
                {
                    if (User.IsInRole(JWMaps.Models.RoleName.CanManageHouseholders) ||
                    User.IsInRole(JWMaps.Models.RoleName.CanAdministrate))
                    {
                        <td>@Html.ActionLink(@Model[i].Name, "Edit", "Householders", new { id = Model[i].Id }, null)</td>
                    }
                    else
                    {
                        <td>@Model[i].Name</td>
                    }
                }
                else
                {
                    if (User.IsInRole(JWMaps.Models.RoleName.CanManageHouseholders) ||
                    User.IsInRole(JWMaps.Models.RoleName.CanAdministrate))
                    {
                        <td>@Html.ActionLink("Não informado", "Edit", "Householders", new { id = Model[i].Id }, null)</td>
                    }
                    else
                    {
                        <td>Não informado</td>
                    }
                }
                <td><a href="http://maps.google.com/maps?q=loc:@Model[i].Latitude,@Model[i].Longitude&navigate=yes">@Model[i].Address</a></td>
                @*<td>@Model[i].Address</td>*@
                @if (@Model[i].Visits != null)
                {
                    if (@Model[i].Visits.Count > 0)
                    {
                        <td> @Model[i].Visits.OrderBy(v => v.DateOfVisit).Last().DateOfVisit.ToString("dd/MM/yyyy") </td>
                    }
                    else
                    {
                        <td>Ainda não foi visitado</td>
                    }
                }
                else
                {
                    <td>Ainda não foi visitado</td>
                }
                <td>@Html.ActionLink("marcar como \"visitado\"", "SetVisit", "TerritoryMaps", new { id = Model[i].Id }, null)</td>
            </tr>
        }
    </tbody>
</table>

<div class="container">
    <div id="map" class="jumbotron" style="width: 95%; height: 432px" />

    <div>
        @Html.ActionLink("Voltar", "Index")
    </div>
</div>


@section scripts
{
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCDXPe6iLZmeOYItmk84ZuV7wVJ_vSQQQs&sensor=false"></script>
    <script type="text/javascript" language="javascript">
        $(document).ready(function () {
            $("#householders").DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese-Brasil.json"
                }
            });

            function initMap() {

                var householders = $(".addr");
                var latitude = @Html.Raw(Json.Encode(Model.First().Latitude));
                var longitude = @Html.Raw(Json.Encode(Model.First().Longitude));

                var myLatLng = {lat: latitude, lng: longitude};

                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 17,
                    center: myLatLng
                });

                var bounds = new google.maps.LatLngBounds();
                var labels = '123456789';
                var labelIndex = 0;

                @foreach(var householder in Model)
                {
                    <text>

                var marker = new google.maps.Marker({
                    position: new google.maps.LatLng(@householder.Latitude.ToString().Replace(',', '.') , @householder.Longitude.ToString().Replace(',', '.')),
                    map: map,
                    label: labels[labelIndex++ % labels.length]
                });

                bounds.extend(marker.getPosition());
                </text>
                }

                map.fitBounds(bounds);

            } google.maps.event.addDomListener(window, 'load', initMap);
        })
    </script>
}

JWMaps/Views/TerritoryMaps/TerritoryMapView.cshtml
@model List<JWMaps.Models.Householder>

@{
    ViewBag.Title = "TerritoryMapView";
}

<h2>TerritoryMapView</h2>

<table id="householders" class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>#ID</th>
            <th>Name</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
        @for(int i = 0 ; i < Model.Count; i++)
        {
            <tr>
                <td>@(i+1)</td>
                <td>@Html.ActionLink(Model[i].Name, "Edit", "Householders", new { id = Model[i].Id }, null)</td>
                <td>@Model[i].Address</td>
            </tr>
        }
    </tbody>
</table>

<div id="map" style="width: 95%; height: 432px" />


@section scripts
{
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyCDXPe6iLZmeOYItmk84ZuV7wVJ_vSQQQs&sensor=false"></script>
    <script type="text/javascript" language="javascript">
        $(document).ready(function () {
            $("#householders").DataTable();

            function initMap() {

                var householders = $(".addr");
                var latitude = @Html.Raw(Json.Encode(Model.First().Latitude));
                var longitude = @Html.Raw(Json.Encode(Model.First().Longitude));

                var myLatLng = {lat: latitude, lng: longitude};

                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 17,
                    center: myLatLng
                });

                var bounds = new google.maps.LatLngBounds();
                var labels = '123456789';
                var labelIndex = 0;

                @foreach(var householder in Model)
                {
                    <text>

                    var marker = new google.maps.Marker({
                        position: new google.maps.LatLng(@householder.Latitude.ToString().Replace(',', '.') , @householder.Longitude.ToString().Replace(',', '.')),
                        map: map,
                        label: labels[labelIndex++ % labels.length]
                        });
                              
                    bounds.extend(marker.getPosition());                    
                    </text>                    
                }

                map.fitBounds(bounds);

            } google.maps.event.addDomListener(window, 'load', initMap);
        })
    </script>
}